modLoader="javafml"
loaderVersion="[58,)"
license="MIT"
issueTrackerURL="https://github.com/Pinary-Pi/Colored-Bricks-Minecraft-Mod/issues"

[[mods]]
modId="coloredbricks"
version="1.21.8-5.2"
displayName="Colored Bricks Mod"
logoFile="logo.png"
credits="Thank you to those who helped me on the Minecraft Forge Modder Support Forum!"
authors="Pinary_Pi"
description='''
Adds a different variant of each brick for all 16 colors there are in minecraft!
'''

[[dependencies.coloredbricks]]
modId="forge"
mandatory=true
versionRange="[58,)"
ordering="NONE"
side="BOTH"

[[dependencies.coloredbricks]]
modId="minecraft"
mandatory=true
versionRange="[1.21.8,1.22)"
ordering="NONE"
side="BOTH"